@echo off
echo "使用bat脚本来复制文件夹和文件"
echo.
xcopy E:\json\walking-video\person01_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person01_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person01_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person01_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person01_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person01_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person01_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person01_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person02_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person02_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person02_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person02_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person02_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person02_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person02_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person02_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person03_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person03_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person03_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person03_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person03_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person03_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person03_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person03_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person04_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person04_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person04_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person04_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person04_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person04_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person04_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person04_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person05_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person05_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person05_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person05_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person05_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person05_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person05_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person05_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person06_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person06_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person06_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person06_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person06_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person06_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person06_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person06_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person07_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person07_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person07_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person07_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person07_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person07_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person07_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person07_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person08_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person08_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person08_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person08_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person08_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person08_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person08_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person08_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person09_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person09_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person09_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person09_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person09_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person09_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person09_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person09_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person10_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person10_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person10_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person10_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person10_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person10_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person10_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person10_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person11_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person11_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person11_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person11_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person11_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person11_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person11_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person11_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person12_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person12_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person12_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person12_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person12_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person12_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person12_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person12_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person13_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person13_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person13_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person13_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person13_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person13_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person13_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person13_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person14_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person14_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person14_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person14_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person14_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person14_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person14_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person14_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person15_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person15_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person15_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person15_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person15_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person15_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person15_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person15_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person16_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person16_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person16_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person16_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person16_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person16_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person16_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person16_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person17_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person17_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person17_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person17_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person17_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person17_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person17_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person17_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person18_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person18_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person18_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person18_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person18_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person18_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person18_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person18_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person19_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person19_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person19_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person19_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person19_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person19_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person19_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person19_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person20_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person20_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person20_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person20_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person20_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person20_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person20_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person20_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person21_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person21_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person21_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person21_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person21_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person21_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person21_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person21_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person22_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person22_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person22_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person22_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person22_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person22_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person22_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person22_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person23_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person23_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person23_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person23_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person23_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person23_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person23_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person23_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person24_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person24_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person24_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person24_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person24_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person24_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person24_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person24_walking_d4_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person25_walking_d1_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person25_walking_d1_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person25_walking_d2_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person25_walking_d2_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person25_walking_d3_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person25_walking_d3_uncomp\ /s /e /c /y /h /r
xcopy E:\json\walking-video\person25_walking_d4_uncomp\*.* F:\XLDownload\dataSet\KTH\walking\walking-video\person25_walking_d4_uncomp\ /s /e /c /y /h /r
